docs : 도커허브에 이미지 푸쉬 전 JAR파일을 빌드하는 작업을 추가합니다.

diff --git a/.github/workflows/dockerhub-push.yml b/.github/workflows/dockerhub-push.yml
--- a/.github/workflows/dockerhub-push.yml
+++ b/.github/workflows/dockerhub-push.yml
@@ -12,26 +12,45 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v2
+      - uses: actions/checkout@v3
+      - name: Install JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'adopt'
 
-    - name: Build and Push Docker Image
-      env:
-        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-      run: |
-        # Extract branch name from GITHUB_REF
-        BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
+      - uses: actions/cache@v3
+      - name: Gradle Caching
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+          restore-keys: |
+            ${{ runner.os }}-gradle-
+        
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
+      - name: Build with Gradle
+        run: ./gradlew bootJar
 
-        if [ -n "$BRANCH_NAME" ]; then
-          DOCKERFILE_DIR="src/$BRANCH_NAME-service"
-        else
-          echo "Failed to extract branch name from GITHUB_REF."
-          exit 1
-        fi
-
-        cd $DOCKERFILE_DIR
-        docker build -t $DOCKER_USERNAME/$BRANCH_NAME-service:latest .
-        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
-        docker push $DOCKER_USERNAME/$BRANCH_NAME-service:latest
+      - name: Build and Push Docker Image
+        env:
+          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        run: |
+          # Extract branch name from GITHUB_REF
+          BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
+  
+          if [ -n "$BRANCH_NAME" ]; then
+            DOCKERFILE_DIR="src/$BRANCH_NAME-service"
+          else
+            echo "Failed to extract branch name from GITHUB_REF."
+            exit 1
+          fi
+  
+          cd $DOCKERFILE_DIR
+          docker build -t $DOCKER_USERNAME/$BRANCH_NAME-service:latest .
+          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+          docker push $DOCKER_USERNAME/$BRANCH_NAME-service:latest
 
