feat: create Docker Hub push flow (#22)
* feat: create Docker Hub push flow

(cherry picked from commit 0271710bed3ffd641938b10053981668a94d9383)

diff --git a/.github/workflows/dockerhub-push.yml b/.github/workflows/dockerhub-push.yml
--- a/.github/workflows/dockerhub-push.yml
+++ b/.github/workflows/dockerhub-push.yml
@@ -3,35 +3,35 @@ name: Docker Hub Push
 on:
   push:
     branches:
-      - 'timeline/dev'
+      - '**/dev'
+      - '!web/dev'
+      - '!android/dev'
 
 jobs:
-  build:
+  build-and-push:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+    - name: Checkout Repository
+      uses: actions/checkout@v2
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
-        with:
-          java-version: '17'
-          distribution: 'temurin'
+    - name: Build and Push Docker Image
+      env:
+        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      run: |
+        # Extract branch name from GITHUB_REF
+        BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
 
-      - name: Grant execute permission for gradlew
-        run: chmod +x src/timeline-service/gradlew
+        if [ -n "$BRANCH_NAME" ]; then
+          DOCKERFILE_DIR="src/$BRANCH_NAME-service"
+        else
+          echo "Failed to extract branch name from GITHUB_REF."
+          exit 1
+        fi
 
-      - name: Build with Gradle
-        run: |
-          cd src/timeline-service
-          ./gradlew clean build
+        cd $DOCKERFILE_DIR
+        docker build -t $DOCKER_USERNAME/$BRANCH_NAME-service:latest .
+        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+        docker push $DOCKER_USERNAME/$BRANCH_NAME-service:latest
 
-      - name: Build Dockerfile and Push Docker Image
-        env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        run: |
-          cd src/timeline-service
-          docker build -t $DOCKER_USERNAME/timeline-service:latest .
-          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
-          docker push $DOCKER_USERNAME/timeline-service:latest
