refactor: update dockerhub push flow (#27)
(cherry picked from commit d9108e94f573bdf5af0eb5d6e953f4bf9a5316e6)

diff --git a/.github/workflows/dockerhub-push.yml b/.github/workflows/dockerhub-push.yml
--- a/.github/workflows/dockerhub-push.yml
+++ b/.github/workflows/dockerhub-push.yml
@@ -3,35 +3,51 @@ name: Docker Hub Push
 on:
   push:
     branches:
-      - 'auth/dev'
+      - '**/dev'
+      - '!web/dev'
+      - '!android/dev'
 
 jobs:
-  build:
+  build-and-push:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+    - name: Checkout Repository
+      uses: actions/checkout@v2
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
-        with:
-          java-version: '17'
-          distribution: 'temurin'
+    - name: Set Environment Variables
+      run: |
+        BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
+        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
 
-      - name: Grant execute permission for gradlew
-        run: chmod +x src/auth-service/gradlew
+    - name: Set up JDK 17
+      uses: actions/setup-java@v2
+      with:
+        java-version: '17'
+        distribution: 'temurin'
 
-      - name: Build with Gradle
-        run: |
-          cd src/auth-service
-          ./gradlew clean build
+    - name: Grant execute permission for gradlew
+      run: chmod +x src/${{ env.BRANCH_NAME }}-service/gradlew
 
-      - name: Build Dockerfile and Push Docker Image
-        env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        run: |
-          cd src/auth-service
-          docker build -t $DOCKER_USERNAME/auth-service:latest .
-          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
-          docker push $DOCKER_USERNAME/auth-service:latest
+    - name: Build with Gradle
+      run: |
+        cd src/${{ env.BRANCH_NAME }}-service
+        ./gradlew clean build
+
+    - name: Build and Push Docker Image
+      env:
+        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+        BRANCH_NAME: ${{ env.BRANCH_NAME }}
+      run: |
+        if [ -n "$BRANCH_NAME" ]; then
+          DOCKERFILE_DIR="src/$BRANCH_NAME-service"
+        else
+          echo "Failed to extract branch name from GITHUB_REF."
+          exit 1
+        fi
+
+        cd $DOCKERFILE_DIR
+        docker build -t $DOCKER_USERNAME/$BRANCH_NAME-service:latest .
+        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+        docker push $DOCKER_USERNAME/$BRANCH_NAME-service:latest
